### ISSUE TITLE
备份用的是哪个爬虫？

### ISSUE THREAD

**Issue by ghost** [bryarrow/backup-for-xiaoyuhao-tiezi#1]
我关注缘吧很久了，想自己备份一些喜欢的帖子，但找不到合适的爬虫。看到这个效果不错，求下载地址，想尝试一下。辛苦楼主了！

**Comment by bryarrow** [comment]
> 我关注缘吧很久了，想自己备份一些喜欢的帖子，但找不到合适的爬虫。看到这个效果不错，求下载地址，想尝试一下。辛苦楼主了！


还需要吗
emmm,这是当时寒假我自己写的一个，应该在我的GitHub上能找到，不过其实不是很好用，效率也低

**Comment by ghost** [comment]
看到了，已下载，自己正在研究中，感谢楼主的辛勤工作！

**Comment by bryarrow** [comment]
不用谢啦，那代码写的挺烂的……
而且没想到会有人用，所以注释并不明白，也没有文档……

**Comment by bryarrow** [comment]
> 看到了，已下载，自己正在研究中，感谢楼主的辛勤工作！

如果需要帮助的话，正月十五开学前我会尽力的【狗头】
